apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
      - name: counter-app
        image: nginx:latest   
        ports:
        - containerPort: 80

