apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort   # Use LoadBalancer if on a cloud provider
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

