# agent_worker/manifests/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: resume-processor
spec:
  selector:
    app: resume-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

